// src/lib/recipe-filters.ts
export const cuisines = [
    { value: 'african', label: 'Africana' },
    { value: 'american', label: 'Americana' },
    { value: 'british', label: 'Británica' },
    { value: 'cajun', label: 'Cajún' },
    { value: 'caribbean', label: 'Caribeña' },
    { value: 'chinese', label: 'China' },
    { value: 'eastern_european', label: 'Europa del Este' },
    { value: 'european', label: 'Europea' },
    { value: 'french', label: 'Francesa' },
    { value: 'german', label: 'Alemana' },
    { value: 'greek', label: 'Griega' },
    { value: 'indian', label: 'India' },
    { value: 'irish', label: 'Irlandesa' },
    { value: 'italian', label: 'Italiana' },
    { value: 'japanese', label: 'Japonesa' },
    { value: 'jewish', label: 'Judía' },
    { value: 'korean', label: 'Coreana' },
    { value: 'latin_american', label: 'Latinoamericana' },
    { value: 'mediterranean', label: 'Mediterránea' },
    { value: 'mexican', label: 'Mexicana' },
    { value: 'middle_eastern', label: 'Medio Oriente' },
    { value: 'nordic', label: 'Nórdica' },
    { value: 'southern', label: 'Sureña' },
    { value: 'spanish', label: 'Española' },
    { value: 'thai', label: 'Tailandesa' },
    { value: 'vietnamese', label: 'Vietnamita' },
  ];
  
  export const diets = [
    { value: 'gluten_free', label: 'Sin gluten' },
    { value: 'ketogenic', label: 'Cetogénica' },
    { value: 'vegetarian', label: 'Vegetariana' },
    { value: 'lacto_vegetarian', label: 'Lacto-vegetariana' },
    { value: 'ovo_vegetarian', label: 'Ovo-vegetariana' },
    { value: 'vegan', label: 'Vegana' },
    { value: 'pescetarian', label: 'Pescetariana' },
    { value: 'paleo', label: 'Paleo' },
    { value: 'primal', label: 'Primal' },
    { value: 'low_fodmap', label: 'Baja en FODMAP' },
    { value: 'whole30', label: 'Whole30' },
  ];
  
  export const intolerances = [
    { value: 'dairy', label: 'Lácteos' },
    { value: 'egg', label: 'Huevo' },
    { value: 'gluten', label: 'Gluten' },
    { value: 'grain', label: 'Granos' },
    { value: 'peanut', label: 'Cacahuete' },
    { value: 'seafood', label: 'Mariscos' },
    { value: 'sesame', label: 'Sésamo' },
    { value: 'shellfish', label: 'Crustáceos' },
    { value: 'soy', label: 'Soja' },
    { value: 'sulfite', label: 'Sulfitos' },
    { value: 'tree_nut', label: 'Frutos secos' },
    { value: 'wheat', label: 'Trigo' },
  ];
  
  export const mealTypes = [
    { value: 'main_course', label: 'Plato principal' },
    { value: 'side_dish', label: 'Guarnición' },
    { value: 'dessert', label: 'Postre' },
    { value: 'appetizer', label: 'Aperitivo' },
    { value: 'salad', label: 'Ensalada' },
    { value: 'bread', label: 'Pan' },
    { value: 'breakfast', label: 'Desayuno' },
    { value: 'soup', label: 'Sopa' },
    { value: 'beverage', label: 'Bebida' },
    { value: 'sauce', label: 'Salsa' },
    { value: 'marinade', label: 'Marinado' },
    { value: 'fingerfood', label: 'Bocadillo' },
    { value: 'snack', label: 'Snack' },
    { value: 'drink', label: 'Bebida' },
  ];